repos:
- repo: local
  hooks:
  -   id: pytest-check
      stages: [commit]
      types: [python]
      name: pytest-check
      entry: python -m pytest
      language: system
      pass_filenames: false
      always_run: true
